export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const AUTH_USER_LOADED = "AUTH_USER_LOADED";
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_ERROR = "USER_ERROR";
export const HIDE_ERROR = "HIDE_ERROR";
export const AUTH_USER_LOADING = "AUTH_USER_LOADING";

export const ADD_ADMIN = 'ADD_ADMIN';
export const UPDATE_ME = 'UPDATE_ME';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';


export const EMAIL_CONFIRM = 'EMAIL_CONFIRM';
export const EMAIL_RESEND = 'EMAIL_RESEND';
export const SET_LOADING_EMAIL = 'SET_LOADING_EMAIL';


export const PHONE_CONFIRM = 'PHONE_CONFIRM';
export const PHONE_RESEND = 'PHONE_RESEND';
export const SET_LOADING_PHONE = 'SET_LOADING_PHONE';