export const GET_ALL_USERS = 'GET_ALL_USERS';
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_ERROR = 'USERS_ERROR';

export const ADD_ADMIN_USERS = 'ADD_ADMIN_USERS';
export const FILTRING_USERS = 'FILTRING_USERS';
export const FILTRING_BLOCK_USERS = 'FILTRING_BLOCK_USERS';
export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_BLOCKED_USERS = 'SEARCH_BLOCKED_USERS';
export const BLOCK_USERS = 'BLOCK_USERS';

