export const GET_ALL_CATSVEH = 'GET_ALL_CATSVEH';
export const CATSVEH_LOADING = 'CATSVEH_LOADING';
export const CATSVEH_ERROR = 'CATSVEH_ERROR';

export const FILTRING_DISPLAY_CATSVEH = 'FILTRING_DISPLAY_CATSVEH';
export const FILTRING_CATSVEH = 'FILTRING_CATSVEH';
export const SEARCH_CATSVEH = 'SEARCH_CATSVEH';

export const GET_ALL_FAMSVEH = 'GET_ALL_FAMSVEH';
export const FAMSVEH_LOADING = 'FAMSVEH_LOADING';
export const SEARCH_FAMSVEH = 'SEARCH_FAMSVEH';
export const FILTRING_DISPLAY_FAMSVEH = 'FILTRING_DISPLAY_FAMSVEH';
export const FILTRING_FAMSVEH = 'FILTRING_FAMSVEH';


export const ONEVEH_LOADING = 'ONEVEH_LOADING';
export const SET_CURRENT_VEH = 'SET_CURRENT_VEH';